// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/IwanPlamboyan/contact-manajemen-golang/app"
	"github.com/IwanPlamboyan/contact-manajemen-golang/config"
	"github.com/IwanPlamboyan/contact-manajemen-golang/controller"
	"github.com/IwanPlamboyan/contact-manajemen-golang/middleware"
	"github.com/IwanPlamboyan/contact-manajemen-golang/repository"
	"github.com/IwanPlamboyan/contact-manajemen-golang/service"
	"github.com/go-playground/validator"
	"github.com/google/wire"
	"net/http"
)

// Injectors from injector.go:

func InitializedServer() (*http.Server, error) {
	appConfig, err := config.LoadConfig()
	if err != nil {
		return nil, err
	}
	jwtUtil := config.ProvideJWTUtil(appConfig)
	jwtMiddleware := middleware.NewJWTMiddleware(jwtUtil)
	databaseConfig := config.ProvideDatabaseConfig(appConfig)
	db, err := app.Connect(databaseConfig)
	if err != nil {
		return nil, err
	}
	validate := validator.New()
	userRepositoryImpl := repository.NewUserRepository()
	refreshTokenRepositoryImpl := repository.NewRefreshTokenRepository()
	authService := service.NewAuthService(db, validate, userRepositoryImpl, refreshTokenRepositoryImpl, jwtUtil)
	authController := controller.NewAuthController(authService)
	userService := service.NewUserService(db, validate, userRepositoryImpl)
	userController := controller.NewUserController(userService)
	contactRepositoryImpl := repository.NewContactRepository()
	contactsService := service.NewContactsService(db, validate, contactRepositoryImpl)
	contactController := controller.NewContactController(contactsService)
	addressRepositoryImpl := repository.NewAddressRepository()
	addressService := service.NewAddressService(db, validate, addressRepositoryImpl, contactRepositoryImpl)
	addressController := controller.NewAddressController(addressService)
	router := app.NewRouter(jwtMiddleware, authController, userController, contactController, addressController)
	server := NewServer(router)
	return server, nil
}

// injector.go:

var DatabaseSet = wire.NewSet(config.ProvideDatabaseConfig, app.Connect)

var authSet = wire.NewSet(repository.NewRefreshTokenRepository, wire.Bind(new(repository.RefreshTokenRepository), new(*repository.RefreshTokenRepositoryImpl)), service.NewAuthService, controller.NewAuthController)

var userSet = wire.NewSet(repository.NewUserRepository, wire.Bind(new(repository.UserRepository), new(*repository.UserRepositoryImpl)), service.NewUserService, controller.NewUserController)

var contactSet = wire.NewSet(repository.NewContactRepository, wire.Bind(new(repository.ContactRepository), new(*repository.ContactRepositoryImpl)), service.NewContactsService, controller.NewContactController)

var addressSet = wire.NewSet(repository.NewAddressRepository, wire.Bind(new(repository.AddressRepository), new(*repository.AddressRepositoryImpl)), service.NewAddressService, controller.NewAddressController)
